[build]
# Uncomment the relevant target for your chip here (ESP32, ESP32-S2, ESP32-S3 or ESP32-C3)
#target = "xtensa-esp32-espidf"
#target = "xtensa-esp32s2-espidf"
#target = "xtensa-esp32s3-espidf"
target = "riscv32imc-esp-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash --monitor"
#rustflags = ["--cfg", "espidf_time64"] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110

[target.xtensa-esp32s2-espidf]
linker = "ldproxy"
runner = "espflash --monitor"
#rustflags = ["--cfg", "espidf_time64"] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash --monitor"
#rustflags = ["--cfg", "espidf_time64"] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash --monitor --use-stub"
# Future - necessary for the experimental "native build" of esp-idf-sys with ESP32C3. See also https://github.com/ivmarkov/embuild/issues/16
# For ESP-IDF 5 add `espidf_time64` and for earlier versions - remove this flag: https://github.com/esp-rs/rust/issues/110
rustflags = ["-C", "default-linker-libraries", "--cfg", "esp_idf_log_colors"]

[unstable]
build-std = ["std", "panic_abort"]
#build-std-features = ["panic_immediate_abort"] # Required for older ESP-IDF versions without a realpath implementation

[env]
ESP_IDF_SYS_ROOT_CRATE = { value = "eclss-esp32" }
ESP_IDF_VERSION = { value = "branch:release/v4.4" }
# Builds against ESP-IDF master (mainline)
#ESP_IDF_VERSION = "master"
ESP_IDF_SDKCONFIG_DEFAULTS = { value = "sdkconfig.defaults" }
# see https://docs.rs/embuild/latest/embuild/cargo/fn.workspace_dir.html
CARGO_WORKSPACE_DIR = { value = "", relative = true }