[package]
name = "pmsa003i"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@elizas.website>"]
edition = "2021"
readme = "README.md"
license = "MIT"

[dependencies]
embedded-hal = { version = "0.2.5" }